LeanTask
nrwiersma/ESP8266Scheduler pull request #20
Opened 2021-02-06 16:02 UTC by dbuezas

This PR:
* Removes the main "dummy" task (saves quite some RAM)
* Removed the backwards link in the circular linked list. Instead of this, the call to `begin` stitches the last task to the first one.
* Added LeanTask, which runs in the global context and consumes no RAM
* Added a superclass `ITask` from which both `Task` and `LeanTask` inherit, so that the scheduler doesn't need to care about which kind of task is the current one.
* Documented the new class and its usage.

Caveats of this PR:
* I didn't realise that the version available in the Arduino Library Manager is not the same as the one in github, so this code doesn't build up on the latest commit. (I do not understand what the run groups are in any case.)
* I removed the `if (!setup_done) {` part, as that can run only once in a task. It is suspicious though that you'd have that if it isn't necessary, so please confirm my assumption

2021-02-06 16:03 UTC, dbuezas commented
Closes #18 and #19

2021-02-06 19:02 UTC, nrwiersma requested changes
This removes all support for run groups, which would be moving backwards in my opinion.

2021-02-06 19:11 UTC, dbuezas commented
> This removes all support for run groups, which would be moving backwards in my opinion.

I understand, is there any documentation I can check to understand how they work?

2021-02-06 19:16 UTC, nrwiersma commented
unfortunately not, but you should not need to change this portion of the code anyway. In theory, you should just need to touch the task linking, and make a base task that both tasks inherit from. The base can contain the current run group properties. `shouldRun` can then be used by both as it currently is to work out when a task should run next.

2021-02-07 11:50 UTC, dbuezas commented
And some example code that uses the feature so i can test it with my changes applied?

2021-02-07 11:55 UTC, dbuezas commented
I forgot to ask, it is not intended that more tasks are started after begin, correct?

2021-02-07 11:59 UTC, nrwiersma commented
I dont have any code any more for run groups. Sorry. Yes, the idea is that once `begin` is called, no more tasks should be added.

2021-02-07 20:27 UTC, closed without merging